global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # USB Token Server metrics
  - job_name: 'usb-token-server'
    static_configs:
      - targets: ['usb-token-server:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cache:6379']
    scrape_interval: 30s

  # Nginx metrics (if using nginx_exporter)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-proxy:80']
    scrape_interval: 30s
